services:

  frontend-application:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    container_name: frontend-application
    # env_file:
    #   - .env
    volumes:
      - shared-data:/shared
    ports:
      - "8080:4173"
    networks:
      - server-net
    # depends_on:
    #   - mongo
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M 
        reservations:
          cpus: '0.25'
          memory: 256M 
          
networks:
  server-net:

volumes:
  shared-data: